const weatherCodes = [
  { code: "Clear skies" },
  { code: "Mainly clear, partly cloudy, and overcast" },
  { code: "Mainly clear, partly cloudy, and overcast" },
  { code: "Mainly clear, partly cloudy, and overcast" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "Fog and depositing rime fog" },
  { code: "" },
  { code: "" },
  { code: "Fog and depositing rime fog" },
  { code: "" },
  { code: "" },
  { code: "Drizzle: Light, moderate, and dense intensity" },
  { code: "" },
  { code: "Drizzle: Light, moderate, and dense intensity" },
  { code: "" },
  { code: "Drizzle: Light, moderate, and dense intensity" },
  { code: "Freezing Drizzle: Light and dense intensity" },
  { code: "Freezing Drizzle: Light and dense intensity" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "Rain: Slight, moderate and heavy intensity" },
  { code: "" },
  { code: "Rain: Slight, moderate and heavy intensity" },
  { code: "" },
  { code: "Rain: Slight, moderate and heavy intensity" },
  { code: "Freezing Rain: Light and heavy intensity" },
  { code: "Freezing Rain: Light and heavy intensity" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "Snow fall: Slight, moderate, and heavy intensity" },
  { code: "" },
  { code: "Snow fall: Slight, moderate, and heavy intensity" },
  { code: "" },
  { code: "Snow fall: Slight, moderate, and heavy intensity" },
  { code: "" },
  { code: "Snow grains" },
  { code: "" },
  { code: "" },
  { code: "Rain showers: Slight, moderate, and violent" },
  { code: "Rain showers: Slight, moderate, and violent" },
  { code: "Rain showers: Slight, moderate, and violent" },
  { code: "" },
  { code: "" },
  { code: "Snow showers slight and heavy" },
  { code: "Snow showers slight and heavy" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "" },
  { code: "Thunderstorm: Slight or moderate" },
  { code: "Thunderstorm with slight and heavy hail" },
  { code: "" },
  { code: "" },
  { code: "Thunderstorm with slight and heavy hail" },
];

export { weatherCodes };
